#!/usr/bin/env python
#
# The script is used to mergetheGVCFs into a smaller set
# of file when too many files are present.
#
#
import argparse
import sys


def 

def main():


if __name__ == "__main__":
    main()

